export const meta = {
  title: 'Casa Prefabricada en Madrid',
  subtitle: 'Investigación interactiva: tecnologías, empresas y costes reales',
  researchDate: 'Junio 2026',
  budget: {
    ideal: 200000,
    max: 300000,
    sizeLow: 100,
    sizeHigh: 120,
  },
}

export const techs = [
  {
    id: 'hormigon',
    icon: '🧱',
    name: 'Hormigón prefabricado',
    summary:
      'Muros o módulos 3D de hormigón armado fabricados en fábrica, montados sobre una losa reinforced. Robustez máxima y casi cero mantenimiento.',
    pricePerM2: [1300, 2000],
    timeframe: '3–6 meses',
    energyClass: ['A', 'A+'],
    thermalMass: 'Alta',
    transportWeight: 'Pesado',
    typicalUse: 'Vivienda habitual, climas extremos, diseño contemporáneo',
  },
  {
    id: 'madera',
    icon: '🌲',
    name: 'Madera (entramado ligero / CLT)',
    summary:
      'Estructura de madera laminada o entramado ligero, con gran aislamiento por centímetro y huella de carbono muy baja. Ambiente cálido.',
    pricePerM2: [1200, 1900],
    timeframe: '4–8 meses',
    energyClass: ['A', 'A+'],
    thermalMass: 'Media',
    transportWeight: 'Ligero',
    typicalUse: 'Vivienda eficiente, diseño personalizado, entornos naturales',
  },
  {
    id: 'lsf',
    icon: '🔩',
    name: 'Light Steel Frame (acero galvanizado)',
    summary:
      'Perfiles de acero galvanizado conformados en frío que soportan paneles de cerramiento. Dimensionalmente estable y rápido de montar.',
    pricePerM2: [1350, 1900],
    timeframe: '4–6 meses',
    energyClass: ['A', 'A'],
    thermalMass: 'Baja',
    transportWeight: 'Ligero',
    typicalUse: 'Vivienda modular, ampliaciones, terrenos con cimentación sencilla',
  },
  {
    id: 'sip',
    icon: '🧊',
    name: 'Paneles SIP (OSB + núcleo EPS/PIR)',
    summary:
      'Panel estructural autoportante: dos chapas de OSB вокруг un núcleo de espuma rígida (EPS/PIR). Sin puentes térmicos, enorme airtightness.',
    pricePerM2: [1400, 2200],
    timeframe: '4–8 meses',
    energyClass: ['A', 'A+'],
    thermalMass: 'Baja',
    transportWeight: 'Ligero',
    typicalUse: 'Casi pasiva, bajo consumo energético, autopromotores exigentes',
  },
  {
    id: 'mod3d',
    icon: '📦',
    name: 'Módulos 3D volumétricos',
    summary:
      'Habitaciones o cajas completas fabricadas en fábrica con todas las instalaciones, transportadas como cargas anchas. Máximo control de calidad.',
    pricePerM2: [1350, 2100],
    timeframe: '3–5 meses (en obra)',
    energyClass: ['A', 'A'],
    thermalMass: 'Media',
    transportWeight: 'Pesado + escolta',
    typicalUse: 'Proyectos con logística compleja, máxima rapidez en parcela',
  },
  {
    id: 'contenedor',
    icon: '🚢',
    name: 'Contenedor marítimo reformado',
    summary:
      'Estructura de shipping container reciclado con cerramientos interiores e aislamiento añadido. Estética industrial.',
    pricePerM2: [950, 1800],
    timeframe: '2–4 meses',
    energyClass: ['C', 'B'],
    thermalMass: 'Baja',
    transportWeight: 'Medio',
    typicalUse: 'Segundas residencias, estudios, presupuestos muy ajustados',
  },
]

export const techProsCons = {
  hormigon: {
    pros: ['Robustez estructural muy alta', 'Casi cero mantenimiento', 'Excelente inercia térmica (confort estable)', 'Fácil certificación energética A', 'Ideal en zonas ventosas o extremas'],
    cons: ['Transporte pesado y caro', 'Estética más "bloque contemporáneo"', 'Cimentación puede encarecerse por peso', 'Menos libertad de modificación posterior'],
  },
  madera: {
    pros: ['Ambiente interior cálido', 'Aislamiento excelente por cm', 'Baja huella de carbono', 'Diseño muy personalizable', 'Montaje rápido en obra'],
    cons: ['Requiere protección UV y humedad detallada', 'Percepción de riesgo de incendio/xilófagos (mitigable)', 'Revisión periódica de barnices/juntas', 'Menos masa térmica que el hormigón'],
  },
  lsf: {
    pros: ['Ligero — tolera cimentaciones más sencillas', 'Dimensiónmente estable (sin contracción)', 'Rápido y preciso', 'Sin problemas de humedad por contracción', 'Fácil de ampliar o reconfigurar'],
    cons: ['Poca masa térmica (oscilaciones rápidas)', 'Puentes térmicos si el detalle es malo', 'Acero necesita protección anticorrosión en zonas húmedas', 'Ruido a caja/tambor si no se aísla bien'],
  },
  sip: {
    pros: ['Envolvente continua sin puentes térmicos', 'Airtightness muy alta (cerca de Passivhaus)', 'Montaje muy rápido (1–2 semanas envolvente)', 'Paneles autoportantes, sin estruc. aparte', 'Ahorro energético hasta 50% vs ladrillo'],
    cons: ['OSB orgánico — sellado crítico anti-condensación', 'Núcleo EPS/PIR es combustible (hay que tratar CTE-SI)', 'Requiere instalador formado', 'Modificación posterior complicada', 'Menos masa térmica que hormigón'],
  },
  mod3d: {
    pros: ['Máximo control de calidad en fábrica', 'Lo más rápido en parcela (días)', 'Coste muy predecible', 'Instalaciones ya resueltas al llegar', 'Ideal para repeticiones/proyectos'],
    cons: ['Logística compleja (cargas anchas, escoltas, grúas)', 'Transporte caro en largas distancias', 'Modificación muy difícil post-ensamblaje', 'Puede requerir permisos de transporte especiales'],
  },
  contenedor: {
    pros: ['Punto de entrada más económico', 'Estructura ya resistente (corten)', 'Estética industrial/distintiva', 'Rápido si ya hay stock', 'Transportable en módulos'],
    cons: ['Cumplir CTE para uso permanente es difícil', 'Aislamiento y altura libre se comen espacio interior', 'Percepción de "vivienda barata" en reventa', 'Vida útil condicionada al tratamiento anti-corrosión'],
  },
}

export const companies = [
  {
    name: 'EcoSip House',
    tech: 'sip',
    icon: '🧊',
    location: 'Coslada (Av. de Moscú 1) — Madrid',
    madridRadius: 'Madrid + 100 km',
    scope: 'Kit Básico → Kit + Montaje → Envolvente Premium/Luxury → Llave en mano. Proyecto técnico + visado, licencia, cimentación con losa aislada, fachada VIROC, instalaciones, cocina/baños.',
    priceFrom: 'Llave en mano desde ~600 €/m² (envolvente); turnkey completo a presupuestar',
    url: 'https://www.ecosiphouse.com',
    notes: 'Único especialista SIP con fábrica/oficina en Madrid. U envolvente Luxury = 0,126 W/m²·K (mejor que Passivhaus). Configurador online en <2 min.',
  },
  {
    name: 'Bosq Habitat',
    tech: 'sip',
    icon: '🧊',
    location: 'Nacional (fabricante directo)',
    madridRadius: 'Toda España',
    scope: 'Llave en mano completo con desglose por partidas en 24–48h. Soporte hipoteca-autopromotor.',
    priceFrom: '1.400–2.200 €/m² llave en mano (Madrid/Cataluña)',
    url: 'https://bosqhabitat.es',
    notes: 'Ahorro energético estimado 1.400–2.600 €/año vs ladrillo. Buena documentación.',
  },
  {
    name: 'Modulartis',
    tech: 'hormigon',
    icon: '🧱',
    location: 'C/ Orense 20, Madrid',
    madridRadius: 'Comunidad de Madrid + Málaga + resto España',
    scope: 'Servicio 360°: asesoramiento hipotecario + estudio técnico + proyecto + construcción + dirección de obra + entrega.',
    priceFrom: 'A presupuestar (rango medio-alto)',
    url: 'https://modulartis.com',
    notes: 'Muros de hormigón prefabricado. Tiempo medio 5 meses. Asesoramiento hipotecario gratuito.',
  },
  {
    name: 'Atlántida Homes (Grupo Riofrío)',
    tech: 'hormigon',
    icon: '🧱',
    location: 'C/ Pez Austral 2 (Retiro), Madrid',
    madridRadius: 'Comunidad de Madrid',
    scope: 'Llave en mano completo: estudio urbanístico, geotécnico, proyecto, licencia, cimentación, montaje, dirección facultativa, certificados.',
    priceFrom: 'Modelo más pequeño desde 512.000 € (226 m²) — gama alta',
    url: 'https://atlantidahomes.com/casas-prefabricadas-madrid/',
    notes: 'Estructura hormigón + acero. Construcción 4 meses en fábrica. Orientado a gama alta, probablemente por encima de presupuesto.',
  },
  {
    name: 'Easy Haus',
    tech: 'hormigon',
    icon: '🧱',
    location: 'Pozuelo de Alarcón (C/ Joaquín Turina 2)',
    madridRadius: 'Comunidad de Madrid y limítrofes',
    scope: 'Sin modelos cerrados: proyecto 100% a medida. Proyecto, licencia, fabricación, montaje, acabados, entrega. Presupuesto cerrado.',
    priceFrom: 'A presupuestar (rango medio-alto, paneles de hormigón)',
    url: 'https://easyhaus.es',
    notes: 'Han construido en Moralzarzal, Miraflores, Majadahonda, Villaviciosa. 6–9 meses. IVA al 10% confirmado para vivienda habitual.',
  },
  {
    name: 'Prefabrik',
    tech: 'hormigon',
    icon: '🧱',
    location: 'Envío a Madrid',
    madridRadius: 'Toda España',
    scope: 'Catálogo con modelos. Llave en mano. Fabricación íntegra en España, mayormente personalizables.',
    priceFrom: 'Elite: 110 m², 3 dorm., 2 baños, 1 garaje — 245.000 € (+IVA probable)',
    url: 'https://prefabrik.es/casas-prefabricadas-madrid/',
    notes: 'Modelo "Unique" 70 m² = 98.000 €. Fortis 250 m² = 465.000 €. Precios catálogo como referencia.',
  },
  {
    name: 'Zero Housing',
    tech: 'lsf',
    icon: '🔩',
    location: 'Fábrica en Padrón (A Coruña)',
    madridRadius: 'Toda España; recargo de transporte >120 km de fábrica',
    scope: 'ZH-103: losa 25 cm incluida, geotécnico, proyecto, licencia, montaje, aerotermia, cocina y baños. Precio cerrado.',
    priceFrom: '165.000 € + 10% IVA (103 m²) — el modelo publicado más cercano a tu objetivo',
    url: 'https://zerohousing.es/viviendas-modulares-prefabricadas/modelo-zh-103/',
    notes: 'Acometidas, cimentación no estándar, coordinación SyS y tasas municipales NO incluidos. Plazo 6 meses.',
  },
  {
    name: 'Madrid Modular',
    tech: 'hormigon',
    icon: '🧱',
    location: 'Agregador para Madrid',
    madridRadius: 'Comunidad de Madrid',
    scope: 'Catálogo de hormigón, madera, contenedor, pasiva. Precios desde 1.400 €/m² con buenas calidades.',
    priceFrom: 'Hormigón desde 135.000 € (90 m²) · Madera desde 170.000 € (90 m²) · Contenedor 95.000 € (60 m²)',
    url: 'https://madridmodular.es/precios-y-modelos/',
    notes: 'Calculadora interactiva online usando hormigón/madera/contenedor/pasiva y calidad.',
  },
  {
    name: 'La Fábrica de Casas',
    tech: 'hormigon',
    icon: '🧱',
    location: 'Toda España',
    madridRadius: 'Toda España',
    scope: 'Catálogo modular de hormigón. Modelos económicos (50/80/120 m²). Llave en mano.',
    priceFrom: '120 m² (4 dorm., 2 baños) catálogo: 84.900 € base',
    url: 'https://lafabricadecasas.es/casas-modulares-de-100m2/',
    notes: 'Verificar exactamente qué incluye el base — probablemente NO incluye cimentación/acometidas/proyecto.',
  },
  {
    name: 'Modulares S&R (Grupo Avante 360)',
    tech: 'sip',
    icon: '🧊',
    location: 'Valencia (C/ Daoiz y Velarde 12)',
    madridRadius: 'Toda España',
    scope: 'Kit Básico (estructura) → Kit Comfort → Llave en mano. Tecnología SIP con aditivo ignífugo.',
    priceFrom: 'Kit Básico: 395 €/m² · Kit Comfort: 950 €/m² · Llave en mano a presupuestar',
    url: 'https://syrfabricamodulares.com/precios-sip',
    notes: 'Opción económica kit autopromotor si tienes mano de obra. Valencia — transport a Madrid a presupuestar.',
  },
]

export const includedItems = [
  { area: 'Técnico y legal', items: [
    'Estudio de viabilidad urbanística de la parcela',
    'Levantamiento topográfico + Estudio geotécnico',
    'Proyecto Básico y de Ejecución (arquitecto)',
    'Visado en el Colegio de Arquitectos',
    'Gestión de licencia de obra',
    'Dirección facultativa (arquitecto + aparejador)',
    'Certificado de final de obra + Eficiencia energética',
    'Cédula de habitabilidad y boletines (luz/agua)',
  ]},
  { area: 'Obra civil en parcela', items: [
    'Cimentación estándar (losa de 25 cm reinforced)',
    'Transporte desde fábrica hasta la parcela',
    'Alquiler de autogrúa para montaje',
    'Montaje e interconexión de módulos/paneles',
    'Acometidas eléctrica, agua, saneamiento, pluviales, telecom',
    'Movimiento de tierras (si necesario)',
  ]},
  { area: 'La vivienda', items: [
    'Fabricación industrial (módulos/paneles)',
    'Estructura y envolvente con aislamiento CTE',
    'Fontanería, saneamiento, electricidad, telecom',
    'Aerotermia (calefacción/ACS/climatización)',
    'Carpintería exterior (ventanas RPT/vidrio doble/triple)',
    'Cocina equipada y baños completos',
    'Acabados interiores (suelos, pintura, carpintería interior)',
    'Iluminación LED',
  ]},
]

export const excludedItems = [
  { label: 'El terreno/parcela', desc: 'No está incluido en ningún presupuesto de casa' },
  { label: 'IVA (10%)', desc: 'Tipo reducido vivienda habitual; aplicado sobre la factura de la casa (no sobre tasas)' },
  { label: 'ICIO (4%)', desc: 'Impuesto de Construcciones, Instalaciones y Obras — 4% del PEM abonado al ayuntamiento' },
  { label: 'Tasa de licencia (~2%)', desc: 'Tasa municipal ~2% del PEM, variable según municipio' },
  { label: 'Altas de suministros', desc: 'Enganches por la compañía (Iberdrola, Canal Isabel II) ~1.000–2.500 €' },
  { label: 'Cimentación no estándar', desc: 'Si el geotécnico exige zapatas/pilotes por mala calidad del terreno' },
  { label: 'Coordinación de Seguridad y Salud', desc: 'Algunos contratos NO la incluyen (Zero Housing, por ejemplo)' },
  { label: 'Extras (valla, piscina, domótica, fotovoltaica)', desc: 'Opcionales, no incluidos' },
]

export const costByQuality = {
  low: { label: 'Calidad media (objetivo 200k)', pctPerM2: 1450, energyClass: 'A' },
  high: { label: 'Calidad alta (hasta 300k)', pctPerM2: 1800, energyClass: 'A+' },
}

export const costBreakdownPercents = {
  cimentacion: 0.1,
  estructura: 0.24,
  cubierta: 0.1,
  carpinteria: 0.1,
  revestimientos: 0.07,
  instalaciones: 0.215,
  acabados: 0.15,
  direccion: 0.04,
}

export const extraCosts = {
  acometidas: [2000, 5000],
  earthworks: [1500, 4000],
  altas: [1000, 2500],
  fencing: [3000, 8000],
  porch: [4000, 10000],
  photovoltaic: [6000, 12000],
}

export const pitfalls = [
  { title: 'Cimentación no incluida en el catálogo', detail: 'Muchos precios de catálogo (La Fábrica de Casas, Charlesson) muestran solo el módulo de fábrica. La losa puede sumar 8.000–14.000 €. Pregunta siempre qué incluye.' },
  { title: 'Acometidas casi siempre extra', detail: 'Las conexiones a la red (luz, agua, saneamiento, pluviales) se miden por metros de zanja y rara vez están incluidas. Zero Housing las lista en "a valorar en cada proyecto".' },
  { title: 'Recargo de transporte >120 km', detail: 'Zero Housing añade recargo pasado 120 km de su fábrica. Módulos de hormigón pesan más y son más caros de transportar — elegir empresa cerca de Madrid reduce este riesgo.' },
  { title: 'Impuestos a tu cargo', detail: 'ICIO 4% + tasa licencia ~2% = ~6% del PEM son pagos al ayuntamiento que NO hace el constructor. Súmalos siempre al presupuesto.' },
  { title: 'IVA al 10% (no 21%)', detail: 'Solo si es vivienda habitual. Hipoteca y financiació. Confirmar con entidad bancaria. Modulartis ofrece asesoramiento hipotecario gratuito.' },
  { title: 'Tipo de suelo en Madrid', detail: 'Suelos arcillosos en la cuenca, granito en la Sierra. El geotécnico determina el coste de cimentación. Realizar antes de comprar el terreno.' },
  { title: 'Suelo rústico en la Sierra', detail: 'Construir nueva vivienda en suelo rústico en la Sierra de Madrid está casi prohibido salvo casos específicos. Confirmar viabilidad urbanística ANTES de comprar la parcela.' },
  { title: 'Plazos y burocracia', detail: 'Fábrica 4–6 meses, montaje 1–2 semanas, licencia 2–6 meses (según municipio). Realista: 6–12 meses contrato→llaves.' },
  { title: 'SIPs: exigir ETA', detail: 'Solo aceptar paneles con Evaluación Técnica Europea (ETA). Bancos y notarios la piden cada vez más para mortgages.' },
  { title: 'SIPs: airtightness es TODO', detail: 'Una envolvente SIP mal sellada funciona peor que un entramado. Usar instalador certificado (EcoSip, Bosq, Modulares S&R) y pedir prueba de blower-door.' },
  { title: 'SIPs: condensación y VMC', detail: 'El OSB se pudre si hay condensación. Siempre con lámina de control de vapor + VMC (Ventilación Mecánica Controlada). Nunca aceptar SIP sin VMC.' },
  { title: 'SIPs: resistencia al fuego', detail: 'El EPS/PIR lleva retardantes pero es combustible. CTE DB-SI requiere acabados (pladur/VIROC) en cara interior. Verificar en memoria de calidades.' },
]

export const sources = [
  { label: 'idealista news (dic 2025)', url: 'https://www.idealista.com/news/inmobiliario/vivienda/2025/12/02/874777-casas-prefabricadas-llave-en-mano-opciones-listas-para-entrar-a-vivir' },
  { label: 'habitissimo guía de precios', url: 'https://www.habitissimo.es/presupuestos/construir-casa-prefabricada-llave-en-mano' },
  { label: 'caasa.es — paneles SIP', url: 'https://caasa.es/construccion-paneles-sip/' },
  { label: 'Bosq Habitat', url: 'https://bosqhabitat.es/blog/cuanto-cuesta-casa-panel-sip/' },
  { label: 'EcoSip House', url: 'https://www.ecosiphouse.com/precios-y-servicios/' },
  { label: 'Atlántida Homes', url: 'https://atlantidahomes.com/casas-prefabricadas-madrid/' },
  { label: 'Modulartis', url: 'https://modulartis.com/' },
  { label: 'Easy Haus', url: 'https://easyhaus.es/casas-prefabricadas-llave-en-mano-madrid/' },
  { label: 'GoPrefabricadas', url: 'https://goprefabricadas.com/casas-prefabricadas-madrid/' },
  { label: 'Prefabrik', url: 'https://prefabrik.es/casas-prefabricadas-madrid/' },
  { label: 'Zero Housing ZH-103', url: 'https://zerohousing.es/viviendas-modulares-prefabricadas/modelo-zh-103/' },
  { label: 'Madrid Modular', url: 'https://madridmodular.es/precios-y-modelos/' },
  { label: 'La Fábrica de Casas', url: 'https://lafabricadecasas.es/casas-modulares-de-100m2/' },
  { label: 'Modulares S&R (Grupo Avante 360)', url: 'https://syrfabricamodulares.com/precios-sip' },
  { label: 'MimVerd (SIP Modular)', url: 'https://mimverd.com/viviendas/precio-y-compra-de-paneles-sip-en-espana-cuanto-cuesta-construir-con-sip-modular/' },
  { label: 'Charlesson', url: 'https://charlessonhome.es/casasprefabricadas/madrid' },
]

export const questionsToAsk = [
  '¿El precio incluye la cimentación? ¿Cómo es la losa (espesor, reinforced)? Si no, cóbrame aparte.',
  '¿Incluye las acometidas (trenches a red eléctrica, agua, saneamiento)? ¿Cómo se miden?',
  '¿Está incluido el IVA? ¿ Está incluido el ICIO y la tasa de licencia?',
  '¿Quién hace la Coordinación de Seguridad y Salud?',
  '¿Qué certificación tiene el panel / la estructura (ETA, CE, ISO)?',
  '¿Pueden dar 3 referencias de clientes en Madrid y visitar una vivienda entregada?',
  '¿Cuál es el plazo de fábrica + montaje? ¿Hay penalización si se retrasa?',
  '¿Incluye aerotermia + VMC de serie? ¿Y cocina equipada y baños?',
  '¿La hipoteca autopromotor está soportada por la empresa? ¿Tienen banco colaborador?',
  'Si el geotécnico revela que el suelo es malo, ¿cómo se ajusta el presupuesto de cimentación?',
]

export const visitPlaces = [
  {
    name: 'Acerormigón — Exposición de Casas',
    type: 'showroom',
    icon: '🏭',
    address: 'San Sebastián de los Reyes, A-1 km 27 (salida 26), Madrid',
    hours: 'Lun–Jue 9:30–14:00 y 15:00–19:00 · Vie 9:30–14:00',
    appointment: 'Cita previa requerida · Tel. 682 49 58 46',
    what: 'Mayor exposición de casas de acero y hormigón de la Comunidad de Madrid. Modelos en 1 y 2 plantas. Solo cita previa.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Acerormigon%20San%20Sebastian%20de%20los%20Reyes%20Madrid',
    url: 'https://acerormigon.es/visitanos/',
    tech: 'hormigon',
    recommended: true,
  },
  {
    name: 'Casaredia — Exposición de Casas Modulares y Mobil Homes',
    type: 'showroom',
    icon: '🏘️',
    address: 'C. Estrategia 15, Polígono Industrial los Olivos, 28906 Getafe, Madrid',
    hours: 'Lun–Vie 10:00–18:00 · Sábado Santa 10:00–14:00',
    appointment: 'Reserva cita (también videollamada)',
    what: 'Mayor exposición de mobil homes y casas modulares de España. Modelos propios (Universal, Grand Luxe) desde 70k. Ferias periódicas con ofertas. Más de 20 años en el sector.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Casaredia%20Getafe%20C%20Estrategia%2015',
    url: 'https://casaredia.com/madrid/',
    tech: 'mod3d',
    recommended: true,
  },
  {
    name: 'Modulartis — Casa piloto',
    type: 'pilot',
    icon: '🏠',
    address: 'Sierra Noroeste de Madrid (ubicación exacta al reservar)',
    hours: 'Visita con cita previa · Mañana o tarde',
    appointment: 'Formulario online o tel. 910 467 187',
    what: 'Casa modular de hormigón totalmente terminada en la sierra de Madrid. Oficina en C/ Orense 20, planta 1, oficina 10, 28020 Madrid.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Modulartis%20Orense%2020%20Madrid',
    url: 'https://modulartis.com/casa-piloto-modulartis/',
    tech: 'hormigon',
    recommended: true,
  },
  {
    name: 'Atlántida Homes — Showroom',
    type: 'office',
    icon: '🏢',
    address: 'C/ Pez Austral 2 (Retiro), Madrid',
    hours: 'Con cita previa',
    appointment: 'Tel. 914 09 71 80',
    what: 'Oficina de Grupo Riofrío en el centro de Madrid. No es casa piloto pero sí showroom con materiales, acabados y modelos de hormigón+acero. Gama alta.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Pez%20Austral%202%20Madrid',
    url: 'https://atlantidahomes.com/casas-prefabricadas-madrid/',
    tech: 'hormigon',
  },
  {
    name: 'EcoSip House — Oficina + casa SIP',
    type: 'pilot',
    icon: '🧊',
    address: 'Av. de Moscú 1, Coslada, Madrid',
    hours: 'Solo con cita previa (WhatsApp)',
    appointment: 'Tel. 665 964 071 / 617 008 642',
    what: 'El único especialista SIP con base en Madrid. Puedes ver su sistema de paneles SIP, fachada VIROC y configurador online. Llave en mano Premium/Luxury.',
    maps: 'https://www.google.com/maps/search/?api=1&query=EcoSipHouse%20Av%20Moscu%201%20Coslada',
    url: 'https://www.ecosiphouse.com/precios-y-servicios/',
    tech: 'sip',
    recommended: true,
  },
  {
    name: 'Easy Haus — Oficina',
    type: 'office',
    icon: '🏢',
    address: 'C/ Joaquín Turina 2, planta baja, oficina 3, Pozuelo de Alarcón, 28224 Madrid',
    hours: 'Con cita previa',
    appointment: 'Email info@easyhaus.es',
    what: 'Empresa local de Pozuelo especializada en casas a medida con paneles de hormigón. Han construido en Moralzarzal, Miraflores, Majadahonda y Villaviciosa de Odón.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Joaquin%20Turina%202%20Pozuelo%20de%20Alarcon',
    url: 'https://easyhaus.es/casas-prefabricadas-llave-en-mano-madrid/',
    tech: 'hormigon',
  },
  {
    name: 'Zero Housing — Casa piloto',
    type: 'pilot',
    icon: '🔩',
    address: 'Padrón (A Coruña) — no en Madrid',
    hours: 'Visita con cita reservada',
    appointment: 'Reserva de cita para tour virtual',
    what: 'Casa piloto ZH-103 de 103 m². Mismo modelo que se ofrece a clientes. Galicia, no Madrid, pero es la única casa SIP-LSF terminada visitable de la marca.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Zero%20Housing%20Padron%20A%20Coruna',
    url: 'https://zerohousing.es/viviendas-modulares-prefabricadas/modelo-zh-103/',
    tech: 'lsf',
  },
  {
    name: 'Casas Carbonell — Fábrica y exposición',
    type: 'factory',
    icon: '🌲',
    address: 'Valencia (cita para visita personalizada)',
    hours: 'Con cita previa',
    appointment: 'Contactar vía web',
    what: 'Fábrica de casas modulares de madera. Se puede ver el proceso de ensamblaje y casas terminadas. No en Madrid, pero visita personalizada al completo.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Casas%20Carbonell%20Valencia',
    url: 'https://www.casascarbonell.com/exposicion-de-casas-modulares/',
    tech: 'madera',
  },
  {
    name: 'Bosq Habitat — Visita de proyecto',
    type: 'office',
    icon: '🧊',
    address: 'Contacto online · national',
    hours: 'Presupuesto desglosado en 24–48h',
    appointment: 'Formulario web',
    what: 'Fabricante directo de paneles SIP. No tiene showroom físico en Madrid, pero ofrece visita a proyectos entregados y presupuesto detallado rápido. Soporte para hipoteca autopromotor.',
    maps: '',
    url: 'https://bosqhabitat.es/blog/cuanto-cuesta-casa-panel-sip/',
    tech: 'sip',
  },
  {
    name: 'Nex Modular Homes — Casa piloto',
    type: 'pilot',
    icon: '📦',
    address: 'Madrid (cita previa)',
    hours: 'Con cita previa',
    appointment: 'Reserva via web',
    what: 'Casas modulares móviles sin obra. Visita a casa piloto para sentir el diseño y acabados. Enfoque en móviles/no permanentes.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Nex%20Modular%20Homes%20Madrid',
    url: 'https://nexmodularhomes.com/',
    tech: 'mod3d',
  },
]

export const visitPlacesAlicante = [
  {
    name: 'Alucasa — Fábrica y exposición',
    type: 'factory',
    icon: '🏭',
    address: 'Paraje de las Bóvedas 96, Polígono El Raiguero, 03160 Almoradí, Alicante',
    hours: 'Lun–Vie 9:30–17:00',
    appointment: 'Cita previa · Tel. 965 702 697',
    what: 'Mayor fabricante de casas móviles y mobil homes de España desde 1977. 35.000 m² de instalaciones. Exposición con modelos visitable. Casas personalizables, instalación en 24h. Merece la pena: es la mayor fábrica del sector mobil home del país.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Alucasa%20Almoradi%20Alicante%20Bovedas%2096',
    url: 'https://www.alucasa.com/contacto/',
    tech: 'mod3d',
    recommended: true,
    alicante: true,
  },
  {
    name: 'Casas inHAUS — inHAUS Lab',
    type: 'factory',
    icon: '🏠',
    address: 'Av. de Picassent 12, 46440 Almussafes, Valencia (a 2h30 desde Madrid)',
    hours: 'Lun–Vie 9:00–14:00 y 15:00–18:00 · Cita previa obligatoria',
    appointment: 'Tel. 963 519 219',
    what: 'Fábrica y showroom de 4.000 m² de casas modulares premium. 111 modelos, 20 nuevos. Equipo técnico, showroom de materiales y proceso de fabricación completo. Jornadas de puertas abiertas periódicas. Una de las pocas fábricas con recorrido técnico completo.',
    maps: 'https://www.google.com/maps/search/?api=1&query=inHAUS%20Av%20Picassent%2012%20Almussafes%20Valencia',
    url: 'https://casasinhaus.com/contacto/',
    tech: 'madera',
    recommended: true,
    alicante: true,
  },
  {
    name: 'Casas Carbonell — Fábrica',
    type: 'factory',
    icon: '🌲',
    address: 'C/ Traginers 9, 46117 Bétera, Valencia (a 2h15 desde Madrid)',
    hours: 'Con cita previa',
    appointment: 'Tel. 698 548 180 · info@casascarbonell.com',
    what: 'Fábrica de casas modulares de madera. Visita personalizada: ver casas terminadas y el proceso de ensamblaje. Solo para interesados en madera modular, no para mobil homes.',
    maps: 'https://www.google.com/maps/search/?api=1&query=Traginers%209%20Betera%20Valencia',
    url: 'https://www.casascarbonell.com/contacto/',
    tech: 'madera',
    alicante: true,
  },
]

export const feriasAlicante = [
  {
    name: 'Construmat 2026',
    date: '20–22 mayo 2026',
    address: 'Fira de Barcelona, Gran Vía (Barcelona) — 4h30 desde Madrid',
    what: 'Feria internacional de construcción e innovación sostenible. Vivienda social, biohabitabilidad, industrialización. Dedicada a la innovación disruptiva en construcción: startups, talleres y soluciones modulares.',
    url: 'https://hogarmodular.com/feria-de-casas-prefabricadas-descubre-lo-ultimo-en-viviendas-modulares/',
    alicante: true,
  },
  {
    name: 'CEVISAMA 2026',
    date: '24–28 febrero 2026',
    address: 'Feria Valencia — 1h30 desde Alicante, 2h desde Madrid',
    what: 'Feria internacional de arquitectura cerámica e innovación, pero con presencia creciente de construcción modular e industrializada. Casas inHAUS y otros fabricantes exponen aquí.',
    url: 'https://casasinhaus.com/agenda-ferias-eventos/',
    alicante: true,
  },
]

export const ferias = [
  {
    name: 'REBUILD 2026',
    date: '24–26 marzo 2026',
    address: 'IFEMA Madrid, Feria de Madrid (Metro L8)',
    what: 'La feria líder de construcción industrializada, sostenibilidad e innovación para edificación. +750 firmas expositivas, +30k visitantes profesionales, +700 speakers. Es EL evento para ver modulares, SIP, CLT y todo lo industrializado.',
    url: 'https://www.ifema.es/rebuild',
    recommended: true,
  },
  {
    name: 'Feria Casaredia (Getafe)',
    date: '12–15 marzo 2026 · Eventos periódicos (ene, mar, nov)',
    address: 'C. Estrategia 15, Getafe',
    what: 'Gran feria de mobil homes y casas modulares con descuentos exclusivos. 4 días para recorrer modelos con tranquilidad.',
    url: 'https://casaredia.com/feria-mobil-homes-casas-modulares/',
  },
  {
    name: 'Feria Caravaning Madrid (Xanadú)',
    date: '5–9 noviembre 2026',
    address: 'Parking exterior C.C. intu Xanadú, A5 salidas 22–23',
    what: 'Autocaravanas, caravanas y mobile homes nuevas y de ocasión. Descuentos durante la feria. Útil para ver opciones económicas modulares móviles.',
    url: 'https://casaredia.com/madrid/',
  },
]