export const meta = {
  researchDate: 'Julio 2026',
  portfolio: '€2.000.000',
  buildBudget: '€300.000',
  plotTarget: '€50.000',
}

export const locations = [
  {
    id: 'villarejo',
    icon: '🏡',
    emoji: '📍',
    nameEs: 'Villarejo de Salvanés',
    nameEn: 'Villarejo de Salvanés',
    regionEs: 'Madrid',
    regionEn: 'Madrid Province',
    taglineEs: 'El corredor de la A-3',
    taglineEn: 'The A-3 Commuter Corridor',
    plotPrice: [40000, 50000],
    plotSize: [300, 500],
    wealthTax: 0,
    wealthTaxNoteEs: '€0/aporte — 100% bonificación en Madrid',
    wealthTaxNoteEn: '€0/year — 100% Madrid rebate',
    itpPct: 6,
    buildCost: 260000,
    monthlyExpenses: 3150,
    schoolEs: 'Colegio Santa Elena (concertado bilingüe) o CEIP Nuestra Señora de la Victoria',
    schoolEn: 'Colegio Santa Elena (bilingual concertado) or CEIP Nuestra Señora de la Victoria',
    schoolUrl: 'https://www.colegiosantaelena.com/',
    mallEs: 'CC H2O Rivas — 22 min por la A-3',
    mallEn: 'CC H2O Rivas — 22 min via A-3',
    mallUrl: 'https://www.h2occ.com',
    sportsEs: 'Polideportivo Municipal Mariano Díaz · pádel vía Playtomic',
    sportsEn: 'Polideportivo Municipal Mariano Díaz · padel via Playtomic',
    sportsUrl: 'https://playtomic.io',
    commutes: [
      { labelEs: 'Centro de Madrid (Puerta del Sol)', labelEn: 'Madrid Center (Puerta del Sol)', time: '40–45 min' },
      { labelEs: 'CC H2O Rivas', labelEn: 'CC H2O Rivas', time: '22 min' },
      { labelEs: 'Colegios locales', labelEn: 'Local schools', time: '2–5 min' },
    ],
    recommendationEs: 'Mejor opción dentro de Madrid: A-3 directa, €0 impuesto, colegios a 2 min.',
    recommendationEn: 'Best Madrid-province option: A-3 access, €0 tax, schools 2 min away.',
    recommended: true,
    activities: [
      { icon: '🏰', nameEs: 'Castillo-Torre del Homenaje', nameEn: 'Castle-Keep Tower', descEs: 'Torre medieval única con cubillos semicilíndricos. Museos dentro. Visitas teatralizadas para niños los fines de semana.', descEn: 'Unique medieval tower with semicircular bastions. Museums inside. Theatrical tours for kids on weekends.', url: 'https://www.turismovillarejodesalvanes.com/index.php' },
      { icon: '🎬', nameEs: 'Museo del Cine Profesional', nameEn: 'Professional Cinema Museum', descEs: 'Primer museo del cine de España: proyectores, carteles y maquinaria de la historia del cine. Cita previa.', descEn: 'Spain\'s first cinema museum: projectors, posters and cinema machinery. By appointment.', url: '' },
      { icon: '🏊', nameEs: 'Piscina Municipal Cubierta', nameEn: 'Indoor Municipal Pool', descEs: 'Piscina cubierta con clases de natación para todas las edades, desde aprendizaje hasta perfeccionamiento.', descEn: 'Indoor pool with swimming lessons for all ages, from beginners to advanced.', url: 'https://www.villarejodesalvanes.es/areas-municipales/deportes-y-espacios-deportivos/piscina-cubierta/' },
      { icon: '🎾', nameEs: 'Polideportivo Mariano Díaz', nameEn: 'Mariano Díaz Sports Center', descEs: 'Pistas de tenis, pádel, fútbol y baloncesto. Actividades deportivas y culturales municipales todo el año.', descEn: 'Tennis, padel, soccer and basketball courts. Municipal sports and cultural activities year-round.', url: 'https://www.villarejodesalvanes.es/areas-municipales/deportes-y-espacios-deportivos/' },
      { icon: '🎭', nameEs: 'Escuela Municipal de Música', nameEn: 'Municipal Music School', descEs: 'Escuela de música municipal con clases para niños y adultos. Inscripción anual en septiembre.', descEn: 'Municipal music school with classes for children and adults. Annual enrollment in September.', url: 'https://www.villarejodesalvanes.es/relacion-de-actividades-deportivas-y-culturales-2025-26/' },
      { icon: '🎪', nameEs: 'Fiestas Patronales (septiembre)', nameEn: 'Patron Saint Festivities (September)', descEs: 'Espectáculos infantiles, parque acuático Aqualand, gigantes y cabezudos, encierros y talleres taurinos infantiles.', descEn: 'Children\'s shows, Aqualand water park, giants & big-heads parade, bull-running and kids\' bull workshops.', url: 'https://elresurgirdemadrid.com/fiestas-patronales-de-villarejo-de-salvanes-2024/' },
      { icon: '🌳', nameEs: 'Casa de la Tercia + Museo Etnográfico', nameEn: 'Casa de la Tercia + Ethnographic Museum', descEs: 'Antiguo centro de la Orden de Santiago, ahora centro de exposiciones con museo etnográfico en la bodega.', descEn: 'Former headquarters of the Order of Santiago, now exhibition center with an ethnographic museum in the cellar.', url: '' },
    ],
  },
  {
    id: 'colmenar',
    icon: '🌳',
    emoji: '📍',
    nameEs: 'Colmenar de Oreja (Urtajo)',
    nameEn: 'Colmenar de Oreja (Urtajo)',
    regionEs: 'Madrid',
    regionEn: 'Madrid Province',
    taglineEs: 'Urbanizaciones estilo americano',
    taglineEn: 'American-style subdivisions',
    plotPrice: [30000, 45000],
    plotSize: [800, 1000],
    wealthTax: 0,
    wealthTaxNoteEs: '€0/aporte — 100% bonificación en Madrid',
    wealthTaxNoteEn: '€0/year — 100% Madrid rebate',
    itpPct: 6,
    buildCost: 255000,
    monthlyExpenses: 3050,
    schoolEs: 'CEIP Apis Aurelia (Colmenar, 10 min) o Colegio Apóstol Santiago en Aranjuez (18 min)',
    schoolEn: 'CEIP Apis Aurelia (Colmenar, 10 min) or Colegio Apóstol Santiago in Aranjuez (18 min)',
    schoolUrl: '',
    mallEs: 'Área comercial de Aranjuez (CC E.Leclerc) — 18 min · CC Plaza Éboli (Pinto) — 25 min',
    mallEn: 'Aranjuez Commercial Area (CC E.Leclerc) — 18 min · CC Plaza Éboli (Pinto) — 25 min',
    mallUrl: '',
    sportsEs: 'Complejo Deportivo Municipal de Colmenar o Club de Padel Aranjuez',
    sportsEn: 'Complejo Deportivo Municipal of Colmenar or Club de Padel Aranjuez',
    sportsUrl: '',
    commutes: [
      { labelEs: 'Centro de Madrid', labelEn: 'Madrid Center', time: '50 min' },
      { labelEs: 'Centro de Aranjuez', labelEn: 'Aranjuez Center', time: '18 min' },
      { labelEs: 'Colegios locales', labelEn: 'Local schools', time: '10–18 min' },
    ],
    recommendationEs: 'Parcelas más grandes dentro de Madrid: 800–1.000 m² por solo €35k.',
    recommendationEn: 'Largest plots inside Madrid: 800–1,000 m² for only €35k.',
    recommended: true,
    activities: [
      { icon: '🥾', nameEs: 'Ruta "Casita del Ratoncito Pérez"', nameEn: '"Mouse Pérez House" Walking Route', descEs: 'Ruta familiar de 2,7 km apta para niños, recorre el casco histórico buscando detalles escondidos.', descEn: '2.7 km family-friendly route, explores the historic town center hunting for hidden details.', url: 'https://turismo.aytocdo.com/rutas-por-colmenar-de-oreja/' },
      { icon: '🌄', nameEs: 'Paseo de los Miradores', nameEn: 'Lookout Walk', descEs: 'Circular de 3 km, fácil, recomendada para niños. Las mejores vistas panorámicas de la comarca.', descEn: '3 km circular, easy, recommended with kids. Best panoramic views of the region.', url: 'https://turismo.aytocdo.com/rutas-por-colmenar-de-oreja/' },
      { icon: '🏛️', nameEs: 'Visita al Casco Histórico (BIC)', nameEn: 'Historic Town Center Tour (BIC)', descEs: 'Conjunto histórico declarado Bien de Interés Cultural. Iglesia Santa María la Mayor, Plaza Mayor porticada, museos.', descEn: 'Historic quarter declared Cultural Heritage Site. Santa María la Mayor church, porticoed main square, museums.', url: 'http://turismo.aytocdo.com/' },
      { icon: '🍷', nameEs: 'Bodegas y Enoturismo', nameEn: 'Wineries & Wine Tourism', descEs: 'Visitas a bodegas y cuevas de vino tradicionales. Cata familiar y cena con espectáculo en Bodegas Peral.', descEn: 'Tours of traditional wine cellars and caves. Family tastings and dinner with show at Bodegas Peral.', url: 'https://turismo.aytocdo.com/' },
      { icon: '🚴', nameEs: 'CiclaMadrid entre Viñedos', nameEn: 'CiclaMadrid Through Vineyards', descEs: 'Ruta MTB/gravel de 15 km entre viñedos, perfecta para hacer en familia con niños que ya pedalean.', descEn: '15 km MTB/gravel route through vineyards, perfect for families with kids who can ride.', url: 'https://turismo.aytocdo.com/rutas-por-colmenar-de-oreja/' },
      { icon: '🌳', nameEs: 'Parque de la Muela + Senderismo', nameEn: 'Parque de la Muela + Hiking', descEs: 'Parque natural con rutas de senderismo de todos los niveles, desde paseos fáciles hasta rutas circulares de 20 km.', descEn: 'Natural park with hiking routes for all levels, from easy walks to 20 km circular routes.', url: 'https://aranjuezya.com.es/que-actividades-se-pueden-hacer-en-familia-en-colmenar-de-oreja/' },
      { icon: '🎨', nameEs: 'Talleres de Arte y Gastronomía', nameEn: 'Art & Food Workshops', descEs: 'Talleres familiares organizados por la Oficina de Turismo: cerámica, cocina tradicional y quesería artesanal.', descEn: 'Family workshops organized by the Tourism Office: pottery, traditional cooking and artisan cheese-making.', url: 'http://turismo.aytocdo.com/' },
    ],
  },
  {
    id: 'nuevo-baztan',
    icon: '🏘️',
    emoji: '📍',
    nameEs: 'Nuevo Baztán (Eurovillas)',
    nameEn: 'Nuevo Baztán (Eurovillas)',
    regionEs: 'Madrid',
    regionEn: 'Madrid Province',
    taglineEs: 'El cinturón este',
    taglineEn: 'The East Commuter Belt',
    plotPrice: [40000, 50000],
    plotSize: [500, 1000],
    wealthTax: 0,
    wealthTaxNoteEs: '€0/aporte — 100% bonificación en Madrid',
    wealthTaxNoteEn: '€0/year — 100% Madrid rebate',
    itpPct: 6,
    buildCost: 260000,
    monthlyExpenses: 3150,
    schoolEs: 'Colegio Internacional Eurovillas o CEIP Juan de Goyeneche (dentro de la urbanización)',
    schoolEn: 'Colegio Internacional Eurovillas or CEIP Juan de Goyeneche (inside the development)',
    schoolUrl: 'https://www.colegiointernacionaleurovillas.com',
    mallEs: 'CC H2O Rivas — 24 min',
    mallEn: 'CC H2O Rivas — 24 min',
    mallUrl: 'https://www.h2occ.com',
    sportsEs: 'Centro Deportivo Eurovillas: tenis, pádel y parques infantiles',
    sportsEn: 'Centro Deportivo Eurovillas: tennis, padel and playgrounds',
    sportsUrl: '',
    commutes: [
      { labelEs: 'Centro de Madrid', labelEn: 'Madrid Center', time: '45 min' },
      { labelEs: 'CC H2O Rivas', labelEn: 'CC H2O Rivas', time: '24 min' },
      { labelEs: 'Colegios locales', labelEn: 'Local schools', time: '2–5 min' },
    ],
    recommendationEs: 'Mayor urbanización de chalets de España, en cuadrícula estilo americano.',
    recommendationEn: 'Largest chalet development in Europe, grid-like American-style layout.',
    recommended: false,
    activities: [
      { icon: '🏊', nameEs: 'Polideportivo Municipal (piscina + pádel + tenis)', nameEn: 'Municipal Sports Center (pool + padel + tennis)', descEs: 'Piscina, fútbol, hockey, baloncesto, tenis y pádel. Abierto todos los días. Clases infantiles.', descEn: 'Pool, soccer, hockey, basketball, tennis and padel. Open daily. Kids\' classes available.', url: 'https://ayto-nuevobaztan.es/polideportivo/' },
      { icon: '🎨', nameEs: 'Extraescolares Colegio Internacional Eurovillas', nameEn: 'Eurovillas School After-School Activities', descEs: 'Ballet, flamenco, zumba, baile urbano, música (Juventudes Musicales), arte, ajedrez, robótica LEGO, pádel, baloncesto, judo, fútbol y patinaje — todo dentro del colegio.', descEn: 'Ballet, flamenco, zumba, urban dance, music, art, chess, LEGO robotics, padel, basketball, judo, soccer and skating — all at school.', url: 'https://www.colegiointernacionaleurovillas.com/servicios/actividades-y-servicios-extraescolares/' },
      { icon: '🗣️', nameEs: 'Kids&Us English (en el cole)', nameEn: 'Kids&Us English (at school)', descEs: 'Inmersión 100% en inglés con método natural, personajes que crecen con el niño. Centro preparador oficial de Cambridge.', descEn: '100% English immersion with natural method, characters that grow with the child. Official Cambridge prep center.', url: 'https://www.colegiointernacionaleurovillas.com/servicios/actividades-y-servicios-extraescolares/' },
      { icon: '🏰', nameEs: 'Palacio de Goyeneche + Iglesia', nameEn: 'Goyeneche Palace + Church', descEs: 'Patrimonio histórico del siglo XVIII._visitas guiadas. Jardines y plazas amplias donde los niños pueden correr.', descEn: '18th-century heritage. Guided tours. Gardens and large squares where kids can run around.', url: 'https://turismo.ayto-nuevobaztan.es/es/servicios-y-actividades/' },
      { icon: '⛺', nameEs: 'Campamento Urbano Municipal', nameEn: 'Municipal Urban Camp', descEs: 'Campamento urbano de septiembre organizado por la concejalía de Infancia para conciliación familiar. Actividades educativas y de ocio.', descEn: 'September urban camp organized by the Childhood council for family conciliation. Educational and leisure activities.', url: 'https://ayto-nuevobaztan.es/guia-de-actividades/' },
      { icon: '🚴', nameEs: 'Rutas de Senderismo y Naturaleza', nameEn: 'Hiking and Nature Routes', descEs: 'Áreas de picnic y rutas de senderismo alrededor de Nuevo Baztán. Día de campo perfecto a 1h de Madrid.', descEn: 'Picnic areas and hiking routes around Nuevo Baztán. Perfect countryside day trip 1h from Madrid.', url: 'https://saposyprincesas.elmundo.es/madrid/lugares/villa-de-nuevo-baztan' },
    ],
  },
  {
    id: 'galapagos',
    icon: '🛡️',
    emoji: '📍',
    nameEs: 'Galápagos (Montelar)',
    nameEn: 'Galápagos (Montelar)',
    regionEs: 'Guadalajara',
    regionEn: 'Guadalajara',
    taglineEs: 'El código trampa en la frontera de Madrid',
    taglineEn: 'The Madrid-border cheat-code',
    plotPrice: [45000, 55000],
    plotSize: [800, 1400],
    wealthTax: 1465,
    wealthTaxNoteEs: '~€122/mes total familia (50/50) — Castilla-La Mancha',
    wealthTaxNoteEn: '~€122/mo total family (50/50) — Castilla-La Mancha',
    itpPct: 9,
    buildCost: 250000,
    monthlyExpenses: 3150,
    schoolEs: 'Colegio Montealbir (concertado bilingüe en El Casar, 5 min) o colegios públicos de Galápagos',
    schoolEn: 'Colegio Montealbir (bilingual concertado in El Casar, 5 min) or public schools in Galápagos',
    schoolUrl: 'https://www.colegiomontealbir.es',
    mallEs: 'CC Plaza Norte 2 (San Sebastián de los Reyes) — 20 min',
    mallEn: 'CC Plaza Norte 2 (San Sebastián de los Reyes) — 20 min',
    mallUrl: 'https://www.plazanorte2.com',
    sportsEs: 'Polideportivo de El Casar (5 min) · pistas internas en Montelar · pádel vía Playtomic',
    sportsEn: 'El Casar sports center (5 min) · internal Montelar courts · padel via Playtomic',
    sportsUrl: 'https://playtomic.io',
    commutes: [
      { labelEs: 'Centro de Madrid', labelEn: 'Madrid Center', time: '45 min' },
      { labelEs: 'CC Plaza Norte 2', labelEn: 'CC Plaza Norte 2', time: '20 min' },
      { labelEs: 'Colegios de El Casar', labelEn: 'El Casar schools', time: '5 min' },
    ],
    recommendationEs: 'Urbanización con seguridad 24h y parcelas gigantes (hasta 1.400 m²). Único con impuesto.',
    recommendationEn: 'Gated community with 24h security and giant plots (up to 1,400 m²). Only one with tax.',
    recommended: false,
    activities: [
      { icon: '🛹', nameEs: 'Pumptrack Park Montelar', nameEn: 'Montelar Pumptrack Park', descEs: 'Circuito de pumptrack para bicis, patinetes y monopatines. Aventuras para niños de todas las edades.', descEn: 'Pumptrack circuit for bikes, scooters and skateboards. Adventures for kids of all ages.', url: 'https://parqueinfantilen.com/pumptrack-park-galapagos-montelar-galapagos/' },
      { icon: '🧗', nameEs: 'Rocódromo Municipal Infantil', nameEn: 'Municipal Kids\' Climbing Wall', descEs: 'Rocódromo infantil instalado en el parque "Manuel García Moreno" por la DG de Juventud y Deportes.', descEn: 'Kids\' climbing wall installed in "Manuel García Moreno" park by the Youth & Sports DG.', url: 'https://www.galapagos.es/' },
      { icon: '📚', nameEs: 'Biblioteca Municipal', nameEn: 'Municipal Library', descEs: 'Espacio cultural con actividades infantiles, cuentacuentos y club de lectura para todas las edades.', descEn: 'Cultural space with children\'s activities, storytelling and reading club for all ages.', url: 'https://www.galapagos.es/' },
      { icon: '⚽', nameEs: 'Campo de Fútbol "Javier Ledesma"', nameEn: '"Javier Ledesma" Soccer Field', descEs: 'Campo de fútbol con césped artificial nuevo. Escuela deportiva municipal para niños.', descEn: 'Soccer field with new artificial turf. Municipal sports school for kids.', url: 'https://www.galapagos.es/' },
      { icon: '🏕️', nameEs: 'Campamento de Verano + Plan Corresponsables', nameEn: 'Summer Camp + Corresponsables Plan', descEs: 'Campamento de verano y servicio de atención infantil municipal (CEI Amapola) para conciliación familiar.', descEn: 'Summer camp and municipal childcare service (CEI Amapola) for family conciliation.', url: 'https://www.galapagos.es/' },
      { icon: '🎨', nameEs: 'Extraescolares Colegio Montealbir', nameEn: 'Montealbir School After-School Activities', descEs: 'Pickleball, fútbol sala, defensa personal, danza/flamenco, karate, escuela de música e idiomas. Rutas de transporte escolar desde Montelar.', descEn: 'Pickleball, indoor soccer, self-defense, dance/flamenco, karate, music school and languages. School bus routes from Montelar.', url: 'https://colegiomontealbir.com/servicios/' },
      { icon: '🚶', nameEs: 'Rutas de Senderismo por Guadalajara', nameEn: 'Hiking Routes in Guadalajara', descEs: 'Rutas y excursiones por el campo y montaña de Guadalajara, aptas para hacer con niños.', descEn: 'Routes and excursions through Guadalajara countryside and mountains, suitable with kids.', url: 'https://saposyprincesas.elmundo.es/actividades-ninos/guadalajara/aire-libre/rutas-y-excursiones' },
    ],
  },
  {
    id: 'las-gabias',
    icon: '☀️',
    emoji: '📍',
    nameEs: 'Las Gabias (Híjar)',
    nameEn: 'Las Gabias (Híjar)',
    regionEs: 'Granada',
    regionEn: 'Granada',
    taglineEs: 'El cinturón de Granada',
    taglineEn: 'The Granada Commuter Belt',
    plotPrice: [45000, 50000],
    plotSize: [350, 450],
    wealthTax: 0,
    wealthTaxNoteEs: '€0/aporte — 100% bonificación en Andalucía',
    wealthTaxNoteEn: '€0/year — 100% Andalucía rebate',
    itpPct: 7,
    buildCost: 220000,
    monthlyExpenses: 2956,
    schoolEs: 'CEIP Pilar Izquierdo (Híjar) o Colegio Internacional Granada en Otura (10 min)',
    schoolEn: 'CEIP Pilar Izquierdo (Híjar) or Colegio Internacional Granada in Otura (10 min)',
    schoolUrl: 'http://www.colegiointernacionalgranada.com',
    mallEs: 'CC Nevada Shopping (el mayor de Andalucía) — 10–12 min',
    mallEn: 'CC Nevada Shopping (largest in Andalucía) — 10–12 min',
    mallUrl: 'https://www.nevada.shopping',
    sportsEs: 'Polideportivo Municipal de Las Gabias y academias de pádel locales',
    sportsEn: 'Polideportivo Municipal de Las Gabias and local padel academies',
    sportsUrl: 'https://playtomic.io',
    commutes: [
      { labelEs: 'Centro de Granada', labelEn: 'Granada Center', time: '15 min' },
      { labelEs: 'CC Nevada Shopping', labelEn: 'CC Nevada Shopping', time: '10–12 min' },
      { labelEs: 'Colegios locales', labelEn: 'Local schools', time: '2–10 min' },
    ],
    recommendationEs: 'El coste de vida más barato de todas las opciones, con €0 impuesto y servicios excelentes.',
    recommendationEn: 'Cheapest cost of living of all options, with €0 tax and excellent services.',
    recommended: true,
    activities: [
      { icon: '🐴', nameEs: 'Finca Malpasillo — Granja Escuela + Equitación', nameEn: 'Finca Malpasillo — Farm School + Horseback Riding', descEs: 'Una de las granjas-escuela más extensas de Andalucía. Clases de equitación, rutas a caballo, paintball, campamentos de verano y cumpleaños.', descEn: 'One of Andalucía\'s largest farm schools. Horseback riding lessons, horse routes, paintball, summer camps and birthdays.', url: 'https://fincamalpasillo.com/' },
      { icon: '⚽', nameEs: 'Escuela de Fútbol Las Gabias', nameEn: 'Las Gabias Football School', descEs: 'Escuela de fútbol municipal con categorías infantiles. Temporada 2026/27 con inscripciones abiertas para niños y niñas.', descEn: 'Municipal football school with youth categories. 2026/27 season enrollment open for boys and girls.', url: 'https://www.lasgabiasesdeporte.com/' },
      { icon: '🎢', nameEs: 'Parque Pocoyo + Parque Gabia Chica', nameEn: 'Pocoyo Park + Gabia Chica Park', descEs: 'Parques infantiles con toboganes, columpios y estructuras de aventura. Zonas verdes donde los niños pueden correr libremente.', descEn: 'Kids\' parks with slides, swings and adventure structures. Green areas where children can run freely.', url: 'https://parqueinfantilen.com/parque-pocoyo-las-gabias/' },
      { icon: '🌅', nameEs: 'Parque Vista Alegre', nameEn: 'Vista Alegre Park', descEs: 'Zonas de juego para niños con columpios, toboganes y estructuras de aventura. Áreas verdes amplias.', descEn: 'Kids\' play areas with swings, slides and adventure structures. Large green spaces.', url: 'https://parqueinfantilen.com/parque-vista-alegre-las-gabias/' },
      { icon: '🏊', nameEs: 'Polideportivo Municipal de Las Gabias', nameEn: 'Las Gabias Municipal Sports Center', descEs: 'Piscina, pistas de pádel y deportes. Academias de pádel locales. Programación de verano con +50 actividades.', descEn: 'Pool, padel courts and sports. Local padel academies. Summer program with 50+ activities.', url: 'https://www.lasgabiasesdeporte.com/' },
      { icon: '🎪', nameEs: 'Programación de Verano Municipal', nameEn: 'Municipal Summer Program', descEs: 'Más de 50 actividades para todas las edades: deportes, cultura, talleres infantiles y eventos nocturnos.', descEn: 'Over 50 activities for all ages: sports, culture, kids\' workshops and evening events.', url: 'https://www.ahoragranada.com/noticias/las-gabias-disena-su-programacion-de-verano-con-mas-de-50-actividades-para-todas-las-edades/' },
      { icon: '🎪', nameEs: 'Periquitos Park — Área Infantil', nameEn: 'Periquitos Park — Kids\' Area', descEs: 'Espacio seguro y recreativo abierto 24h con zonas de juego, áreas de descanso y actividades para niños.', descEn: 'Safe recreational space open 24h with play areas, rest zones and kids\' activities.', url: 'https://periquitospark.es/area-infantil-las-gabias-granada/' },
    ],
  },
]

export const wealthTaxInfo = {
  regions: [
    {
      regionEs: 'Madrid',
      regionEn: 'Madrid',
      rateEn: '€0/year (100% rebate)',
      rateEs: '€0/aporte (100% bonificación)',
      solidarityApplies: false,
      noteEs: 'Bonificación del 100% del Impuesto sobre el Patrimonio. El Impuesto de Solidaridad no aplica porque el patrimonio neto es inferior a €3.000.000.',
      noteEn: '100% Wealth Tax rebate. The Solidarity Tax does not apply since net wealth is under €3,000,000.',
    },
    {
      regionEs: 'Andalucía (Granada)',
      regionEn: 'Andalucía (Granada)',
      rateEn: '€0/year (100% rebate)',
      rateEs: '€0/aporte (100% bonificación)',
      solidarityApplies: false,
      noteEs: 'Andalucía aplica una bonificación del 100% desde 2022. La cuota se elimina por completo si el patrimonio neto está por debajo del umbral del Impuesto de Solidaridad (€3M), como ocurre con el reparto 50/50.',
      noteEn: 'Andalucía applies a 100% regional Wealth Tax rebate since 2022. The full cuota is eliminated when net wealth is under the €3M Solidarity Tax threshold, which holds under a 50/50 split.',
    },
    {
      regionEs: 'Castilla-La Mancha (Guadalajara)',
      regionEn: 'Castilla-La Mancha (Guadalajara)',
      rateEn: '~€1,465/year (~€122/mo) per family (50/50)',
      rateEs: '~€1.465/aporte (~€122/mes) por familia (50/50)',
      solidarityApplies: false,
      noteEs: 'Sin bonificación del 100%. Con el reparto 50/50 cada cónyuge tiene €1.000.000, menos los €700.000 de mínimo exento y los €300.000 de vivienda habitual, la base imponible es muy reducida.',
      noteEn: 'No 100% rebate. With the 50/50 split each spouse has €1,000,000, minus the €700,000 general exemption and €300,000 primary-residence exemption, the taxable base is very low.',
    },
  ],
  excluded: [
    { regionEs: 'Segovia (Castilla y León)', regionEn: 'Segovia (Castilla y León)', reasonEs: 'Sin bonificación del 100%', reasonEn: 'No 100% rebate' },
    { regionEs: 'Zaragoza (Aragón)', regionEn: 'Zaragoza (Aragón)', reasonEs: 'Sin bonificación del 100%', reasonEn: 'No 100% rebate' },
  ],
}

export const splitRules = {
  citations: [
    {
      idEs: 'Artículo 7 · Ley 19/1991',
      idEn: 'Article 7 · Law 19/1991',
      textEs: 'El impuesto tiene carácter estrictamente personal e individual. Cada cónyuge presenta su propia declaración (Modelo 714).',
      textEn: 'The tax has a strictly personal and individual character. Each spouse files their own separate return (Modelo 714).',
    },
    {
      idEs: 'Artículo 7 · Atribución de bienes',
      idEn: 'Article 7 · Asset attribution',
      textEs: 'En bienes gananciales o cuentas conjuntas (cotitularidad), los activos se atribuyen 50% a cada cónyuge salvo prueba en contrario.',
      textEn: 'Under community property or joint accounts (cotitularidad), assets are attributed 50% to each spouse unless proven otherwise.',
    },
    {
      idEs: 'Consultas DGT V2369-21 y V2218-24',
      idEn: 'DGT Rulings V2369-21 and V2218-24',
      textEs: 'La Dirección General de Tributos confirma que los fondos en cuenta conjunta se dividen al 50% entre los titulares para el Impuesto sobre el Patrimonio.',
      textEn: 'The Spanish tax authority confirms that joint account funds are divided equally between titulars for Wealth Tax purposes.',
    },
    {
      idEs: 'Artículo 28 · Mínimo exento',
      idEn: 'Article 28 · Tax-free allowance',
      textEs: 'Cada contribuyente tiene un mínimo exento individual de €700.000 (modificable regionalmente).',
      textEn: 'Each taxpayer gets an individual tax-free allowance of €700,000 (regionally adjustable).',
    },
    {
      idEs: 'Artículo 4.Uno · Vivienda habitual',
      idEn: 'Article 4.Uno · Primary residence',
      textEs: 'Cada contribuyente puede deducir hasta €300.000 por su vivienda habitual.',
      textEn: 'Each taxpayer can deduct up to €300,000 for their primary residence.',
    },
  ],
  howItWorksEs: [
    'Si tu cartera de acciones (ej. Betterment o bróker) está en una cuenta conjunta (JTWROS), Hacienda atribuirá automáticamente el 50% del valor a cada cónyuge.',
    'Esto divide tu cartera de €2.000.000 en dos porciones individuales de €1.000.000 a efectos fiscales.',
    'En una región con €700.000 de exención general (como Castilla-La Mancha) y €300.000 de vivienda habitual, cada cónyuge aplica las deducciones individualmente, reduciendo la base imponible casi a cero.',
  ],
  howItWorksEn: [
    'If your stock portfolio (e.g. Betterment or brokerage) is in a joint account (JTWROS), Hacienda will automatically attribute 50% of the value to each spouse.',
    'This splits your €2,000,000 portfolio into two individual portions of €1,000,000 for tax purposes.',
    'In a region with a €700,000 general exemption (like Castilla-La Mancha) and €300,000 primary-residence exemption, each spouse applies deductions individually, reducing the taxable base to near zero.',
  ],
  preMoveRuleEs: [
    'No esperes a mudarte a España para repartir tus activos.',
    'Si transfieres fondos o acciones de una cuenta individual a la de tu cónyuge o a una cuenta conjunta DESPUÉS de ser residente fiscal en España, Hacienda puede clasificarlo como Donación.',
    'En muchas comunidades (incluida Castilla-La Mancha), las donaciones entre cónyuges no son 100% exemptas y disparan el Impuesto sobre Sucesiones y Donaciones (Ley 29/1987).',
    'Solución: abre cuentas conjuntas y transfiere tus acciones ANTES de mudarte (mientras sigues siendo residente fiscal EE.UU.). Las transferencias entre cónyuges son 100% exemptas en EE.UU. (deducción matrimonial ilimitada) y España no tiene jurisdicción para gravarlas.',
  ],
  preMoveRuleEn: [
    'Do not wait until you move to Spain to split your assets.',
    'If you transfer funds or stocks from a single-owner account to your spouse\'s account or a joint account AFTER becoming a Spanish tax resident, Hacienda can classify it as a Gift (Donación).',
    'In many regions (including Castilla-La Mancha), gifts between spouses are not 100% tax-free and trigger Gift Tax (Ley 29/1987).',
    'Solution: open joint accounts and transfer your stocks BEFORE moving (while still a US tax resident). Spousal transfers are 100% tax-free in the US (unlimited marital deduction) and Spain has no jurisdiction to tax the transaction.',
  ],
  retirementNoteEs: 'Las cuentas de jubilación (401k/IRA) son estrictamente individuales y no pueden hacerse conjuntas. Sin embargo, bajo la ley española, los planes de pensiones (incluidos los 401k/IRA) están exentos del Impuesto sobre el Patrimonio durante la fase de acumulación hasta que comiences a recibir pagos.',
  retirementNoteEn: 'Retirement accounts (401k/IRA) are strictly individual and cannot be made joint. However, under Spanish law, pension plans (including US 401ks/IRAs) are generally exempt from Wealth Tax during accumulation until payouts begin.',
}

export const recommendations = {
  es: [
    { title: 'Si quieres quedarte en Madrid', pick: 'Villarejo de Salvanés', reason: 'Parcela por €45k, colegios públicos, A-3 directa a CC H2O (22 min) y €0 de Impuesto sobre el Patrimonio.' },
    { title: 'Si quieres la parcela más grande en Madrid', pick: 'Colmenar de Oreja (Urtajo)', reason: 'Parcelas de 800–1.000 m² por solo €35k, €0 de Impuesto y los menores gastos mensuales de Madrid, con Aranjuez a 18 min.' },
    { title: 'Si quieres el coste de vida más bajo', pick: 'Las Gabias (Granada)', reason: 'Los menores gastos mensuales de todas las opciones, con €0 de Impuesto y servicios excelentes (CC Nevada a 10 min).' },
  ],
  en: [
    { title: 'If you want to stay in Madrid Province', pick: 'Villarejo de Salvanés', reason: '€45k plot, public schools, easy A-3 drive to CC H2O (22 min) and €0 Wealth Tax.' },
    { title: 'If you want the largest plot in Madrid', pick: 'Colmenar de Oreja (Urtajo)', reason: '800–1,000 m² plots for only €35k, €0 Wealth Tax and the lowest Madrid monthly expenses, with Aranjuez malls/schools 18 min away.' },
    { title: 'If you want the cheapest cost of living', pick: 'Las Gabias (Granada)', reason: 'Lowest monthly expenses of all options, with zero wealth tax and excellent services (CC Nevada 10 min away).' },
  ],
}